sudo: false

language: python
python:
    - "3.6"
    - "3.7"
    - "3.8"
    - "pypy3"
install:
    - pip install -r dev-requirements.txt
    - pip install .
    # black isn't installing on pypy3, so just skip it
    - 'if [ "$TRAVIS_PYTHON_VERSION" != "pypy3" ]; then pip install black; fi'
script:
    - flake8
    - 'if [ "$TRAVIS_PYTHON_VERSION" != "pypy3" ]; then black --check .; fi'
    - py.test
    - make doc

notifications:
  irc:
    channels:
    - "chat.freenode.net#python-effect"
    skip_join: true
    use_notice: true
    template:
      - "%{repository} %{branch} %{commit} by %{author}: %{message}  %{build_url}"
